"""Derive an instrument's marking apparatus from the workbook it wraps.

A workbook instrument carries three things that all say the same thing in different shapes:

  the workbook   every element has `uoc` — the items that element evidences
  the marking    guide criteria A1…An, each with a UoC-traceability line
  the reverse    map: every UoC item the AT claims, against the criterion that evidences it

Hand-maintaining the second and third is how they drift from the first. Here they are DERIVED:
an author declares which tasks each criterion groups, and this module produces the traceability
lines and the reverse map from the workbook's own tags. A tag added to a task appears in its
criterion and in the reverse map without anyone remembering to add it twice.

The verbatim UoC wording in the reverse map is read from the cluster's `consolidated_uoc.md`,
which is the source of truth the transcription and consolidation gates already prove. An item a
criterion claims that does not appear there is a phantom, and `build_reverse_map` raises rather
than printing a plausible-looking row.
"""
# --- FACTORY MIGRATION NOTE --------------------------------------------------
# Before migrating this script into factory/, CHECK factory/common/helpers/ and
# prefer what is there over writing your own. Relevant to this file:
#   docx_template   - clone_block_after() to repeat a heading+table block, and
#                     set_cell_text() which PRESERVES the template's run formatting.
# Every helper is covered by cases in factory/docs/test-plan.md. If one is wrong,
# fix it there and add the case - never fork a local copy.
# -----------------------------------------------------------------------------

import re
from pathlib import Path

__all__ = ["collect_elements", "marking_guide", "load_uoc_text", "build_reverse_map",
           "unevidenced_items", "assemble", "reverse_map_body"]

TAG = re.compile(r"\[((?:[A-Z]{3}[A-Z0-9]+) (?:PC|PE|KE|FS|AC) [^\]]+)\]")


def collect_elements(*lists):
    """Flatten the workbook's content lists into one {task number: element} mapping.

    Questions are keyed "Q<n>" where a task is keyed <n>, so a criterion can group either.
    Pass questions as a (list, "Q") pair; plain lists are treated as tasks.
    """
    out = {}
    for item in lists:
        seq, prefix = item if isinstance(item, tuple) else (item, "")
        for el in seq:
            out[f"{prefix}{el['n']}"] = el
    return out


def _keys(spec):
    """A criterion's `tasks` may be numbers, "Q1"-style strings, or ranges like "1-4"."""
    keys = []
    for entry in spec:
        if isinstance(entry, str) and "-" in entry and entry.replace("-", "").isdigit():
            lo, hi = entry.split("-")
            keys += [str(n) for n in range(int(lo), int(hi) + 1)]
        else:
            keys.append(str(entry))
    return keys


def marking_guide(criteria, elements):
    """[{code, text, tasks}] + the element map → the MARKING rows [statement, uoc_line].

    The UoC line is the union of the tags on the tasks the criterion groups, in the order the
    workbook introduces them, so the line reads in the same order the student meets the work.
    """
    rows = []
    for crit in criteria:
        seen = []
        for key in _keys(crit["tasks"]):
            el = elements.get(key)
            if el is None:
                raise KeyError(f"criterion {crit['code']} names task {key!r}, which does not exist")
            for tag in el.get("uoc", []):
                if tag not in seen:
                    seen.append(tag)
        if not seen:
            raise ValueError(
                f"criterion {crit['code']} groups tasks that carry no UoC tags — it would be a "
                f"free-floating criterion. Tag the tasks, or drop the criterion.")
        rows.append([f"{crit['code']} {crit['text']}",
                     " · ".join(f"[{t}]" for t in seen)])
    return rows


def benchmark_sections(criteria, elements, title):
    """The `BENCHMARK` structure the mapping engine reads: [(section, [(code, text)])].

    The mapping documents are generated by inverting these per-criterion tag lists, so this is
    the same derivation the marking guide uses — one source, three consumers (the marking guide,
    the reverse map, and the Assessment Mapping documents).
    """
    return [(title, [(crit["code"], line)
                     for crit, (_, line) in zip(criteria, marking_guide(criteria, elements))])]


def load_uoc_text(consolidated_path):
    """{tag: verbatim item text} from a cluster's consolidated_uoc.md.

    Reads the bullet lines the consolidation gate validates. The text is everything before the
    tag, with any leading PC numbering left as the unit wrote it.
    """
    text = Path(consolidated_path).read_text(encoding="utf-8")
    out = {}
    for line in text.splitlines():
        line = line.strip()
        if not line.startswith("- "):
            continue
        m = TAG.search(line)
        if not m:
            continue
        body = line[2:m.start()].strip().rstrip("[").strip()
        body = re.sub(r"^\*\*(.+?)\*\*\s*—\s*", r"\1 — ", body)   # FS items lead with a bold name
        body = re.sub(r"<br>", " ", body)
        out[m.group(1)] = body.strip()
    return out


def build_reverse_map(criteria, elements, uoc_text, unit, conditions=None):
    """The reverse-map rows for ONE unit: every tag that unit contributes, → its criteria.

    `conditions` maps an AC tag to the pre-condition that discharges it (e.g. "C1"), because
    assessment conditions are verified before marking rather than evidenced by a criterion.
    """
    by_tag = {}
    for crit in criteria:
        for key in _keys(crit["tasks"]):
            for tag in elements[key].get("uoc", []):
                by_tag.setdefault(tag, [])
                if crit["code"] not in by_tag[tag]:
                    by_tag[tag].append(crit["code"])

    rows = [["UoC item", "Evidenced by criterion(ia)"]]
    missing = []
    for tag in sorted(by_tag, key=_sort_key):
        if not tag.startswith(unit + " "):
            continue
        if tag not in uoc_text:
            missing.append(tag)
            continue
        rows.append([f"[{tag}] {uoc_text[tag]}", " · ".join(by_tag[tag])])
    for tag, where in sorted((conditions or {}).items(), key=lambda kv: _sort_key(kv[0])):
        if tag.startswith(unit + " ") and tag in uoc_text:
            rows.append([f"[{tag}] {uoc_text[tag]}", f"{where} (pre-condition)"])
    if missing:
        raise ValueError(f"phantom tag(s) not in consolidated_uoc.md: {', '.join(missing)}")
    return rows


def unevidenced_items(criteria, elements, uoc_text, expected):
    """Which of the items this AT is expected to evidence no criterion covers.

    The bidirectional check, run at build time so a gap is caught before the docx exists rather
    than by the coverage gate afterwards.
    """
    covered = set()
    for crit in criteria:
        for key in _keys(crit["tasks"]):
            covered.update(elements[key].get("uoc", []))
    return sorted(set(expected) - covered, key=_sort_key)


def _sort_key(tag):
    unit, section, num = tag.split(" ", 2)
    order = {"PC": 0, "PE": 1, "KE": 2, "FS": 3, "AC": 4}.get(section, 9)
    parts = tuple(int(p) for p in num.split(".")) if num.replace(".", "").isdigit() else (99,)
    return (unit, order, parts, num)


# ---------------------------------------------------------------- Kangan assembly

BOILERPLATE = [
    "Add or delete rows as required",
    "If questioning or observation is incorporated into this assessment task, you can incorporate "
    "a Practical Observation Checklist.",
]

INTRO = ("Every UoC requirement this task claims to evidence, with the marking criterion that "
         "evidences it. Each workbook element also carries its own 'Evidences' line, where the "
         "work is actually done. Both this table and the criteria lines are generated from those "
         "element tags, so they cannot drift from the workbook.")


def reverse_map_body(criteria, elements, consolidated_path, units, conditions=None):
    """The assessor-only benchmark section: one reverse-map table per unit.

    `units` is [(unit_code, heading)] — the heading says which of the unit's items this task
    evidences, since a unit is usually split across the cluster's tasks.
    """
    uoc = load_uoc_text(consolidated_path)
    body = [("h1", "Marking Benchmark — UoC traceability (reverse map)"), ("p", INTRO)]
    for unit, heading in units:
        body.append(("p", heading))
        body.append(("tbl", build_reverse_map(criteria, elements, uoc, unit, conditions)))
    return body


def assemble(template_path, spec, mode, render_body, benchmark=None):
    """Fill the institutional Kangan template and render a workbook into it.

    `spec` holds the front matter every instrument supplies: `details`, `overview` /
    `student_overview`, `tasks`, `time_allowed`, `resources` / `student_resources`, `criteria`,
    `conditions`, `criteria_map` and `marking_rows`. `render_body(doc, mode)` renders the
    workbook itself.

    The student template carries one extra leading row in its Details table. That offset is the
    only structural difference between the two templates, and it lives here rather than being
    rediscovered in every builder.
    """
    from docx import Document
    from helpers.docx_tables import clear_table_rows, find_instruction_row, set_cell_content
    from helpers.instrument_layout import render_benchmark

    student = mode != "assessor"
    doc = Document(template_path)

    details = doc.tables[0]
    off = 1 if student else 0
    for i, key in enumerate(("qualification", "units", "task_title", "task_number")):
        set_cell_content(details.rows[1 + off + i].cells[1], spec["details"][key])

    instr = doc.tables[1]
    set_cell_content(find_instruction_row(instr, "Assessment overview"),
                     spec["student_overview"] if student else spec["overview"])
    set_cell_content(find_instruction_row(instr, "Task"), spec["tasks"])
    set_cell_content(find_instruction_row(instr, "Time allowed"), spec["time_allowed"])
    set_cell_content(find_instruction_row(instr, "Resources required"),
                     spec["student_resources"] if student else spec["resources"])
    set_cell_content(find_instruction_row(instr, "Assessment criteria"), spec["criteria"])
    if not student:
        set_cell_content(find_instruction_row(instr, "Location"), "")
        row = instr.add_row()
        set_cell_content(row.cells[0], "Assessment Conditions & Setup Requirements")
        for run in row.cells[0].paragraphs[0].runs:
            run.bold = True
        set_cell_content(row.cells[1], spec["conditions"])

    # The student sees the criterion statements; the assessor sees them with their UoC lines.
    mark = doc.tables[2]
    clear_table_rows(mark, 2)
    rows = ([[f"{c['code']} {c['text']}"] for c in spec["criteria_map"]] if student
            else spec["marking_rows"])
    for lines in rows:
        row = mark.add_row()
        set_cell_content(row.cells[0], lines)
        set_cell_content(row.cells[1], spec.get("check", "☐ Yes  ☐ No"))

    for text in BOILERPLATE:
        for p in doc.paragraphs:
            if p.text.strip() == text:
                p._element.getparent().remove(p._element)
                break

    render_body(doc, mode)

    if not student and benchmark:
        def render_table(d, rws):
            t = d.add_table(rows=len(rws), cols=len(rws[0]))
            try:
                t.style = "Table Grid"
            except KeyError:
                pass
            for r, cells in enumerate(rws):
                for c, val in enumerate(cells):
                    set_cell_content(t.rows[r].cells[c], val)
            d.add_paragraph()

        render_benchmark(doc, benchmark, render_table,
                         {"h1": "Heading 1", "h2": "Heading 2", "p": "Normal"})
    return doc
